apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitnami-sealed-secrets-app
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: bitnami-sealed-secrets/overlays/prod
    repoURL: 'https://github.com/ywy50/k8s-infra'
    targetRevision: main
    kustomize:
      # images: []
      namespace: kube-system
  # sources: []
  project: default
#   syncPolicy:
#     syncOptions:
#     # automated: {}
