apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger-app
spec:
  destination:
    namespace: observability
    server: 'https://kubernetes.default.svc'
  source:
    path: observability/jaeger/overlays/prod
    repoURL: 'https://github.com/ywy50/k8s-infra'
    targetRevision: main
  project: observability
  syncPolicy:
    # automated: {}
    syncOptions:
    - ServerSideApply=true
