apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-app
spec:
  destination:
    namespace: observability
    server: 'https://kubernetes.default.svc'
  source:
    path: observability/prometheus-operator-crds/overlays/prod
    repoURL: 'https://github.com/ywy50/k8s-infra'
    targetRevision: main
  # sources: []
  project: observability
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
