apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-ebs-csi-driver-app
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: aws-ebs-csi-driver/overlays/prod
    repoURL: 'https://github.com/ywy50/k8s-infra'
    targetRevision: main
  project: default
# #   # syncPolicy:
# #   #   syncOptions:  