apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-elasticsearch-operator-app
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: elasticsearch-operator/overlays/prod
    repoURL: 'https://github.com/ywy50/k8s-infra'
    targetRevision: main
  sources: []
  project: default
# #   # syncPolicy:
# #   #   syncOptions: